# Generated by Django 3.0.8 on 2021-06-30 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_todaymenu_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaymenu',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 6, 30, 14, 4, 45, 231767, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('today_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.TodayMenu')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
